version: '3.8'

services:
  backend:
    build: .
    container_name: daddy-leads-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
